In [1]:

import random
random.seed('yll')

In [2]:
s, t = 2, 4
n = 4
plist=[]  # Creating a random parameter list
for i in range(n): 
    plist.append( [ "%s%d" % ( chr(65+i), j+1) for j in range(random.randint(s, t)) ] )
plist

[['A1', 'A2'], ['B1', 'B2'], ['C1', 'C2', 'C3'], ['D1', 'D2', 'D3', 'D4']]

In [3]:
# Here we show how to enumerate all possible parameter lists contents ...
lenpl=[len(plist[x]) for x in range(n)]
lenpl

[2, 2, 3, 4]

In [4]:
import itertools

ranges = [range(x) for x in lenpl]
Alist=[x for x in itertools.product(*ranges) ]
print(Alist, '-->', len(Alist))

[(0, 0, 0, 0), (0, 0, 0, 1), (0, 0, 0, 2), (0, 0, 0, 3), (0, 0, 1, 0), (0, 0, 1, 1), (0, 0, 1, 2), (0, 0, 1, 3), (0, 0, 2, 0), (0, 0, 2, 1), (0, 0, 2, 2), (0, 0, 2, 3), (0, 1, 0, 0), (0, 1, 0, 1), (0, 1, 0, 2), (0, 1, 0, 3), (0, 1, 1, 0), (0, 1, 1, 1), (0, 1, 1, 2), (0, 1, 1, 3), (0, 1, 2, 0), (0, 1, 2, 1), (0, 1, 2, 2), (0, 1, 2, 3), (1, 0, 0, 0), (1, 0, 0, 1), (1, 0, 0, 2), (1, 0, 0, 3), (1, 0, 1, 0), (1, 0, 1, 1), (1, 0, 1, 2), (1, 0, 1, 3), (1, 0, 2, 0), (1, 0, 2, 1), (1, 0, 2, 2), (1, 0, 2, 3), (1, 1, 0, 0), (1, 1, 0, 1), (1, 1, 0, 2), (1, 1, 0, 3), (1, 1, 1, 0), (1, 1, 1, 1), (1, 1, 1, 2), (1, 1, 1, 3), (1, 1, 2, 0), (1, 1, 2, 1), (1, 1, 2, 2), (1, 1, 2, 3)] --> 48


In [32]:
# Given Alist ...
import numpy as np
AA = np.arange(len(Alist)) # len(Alist) == np.prod(lenpl)
AA.shape=tuple(lenpl) # changing indexing methods ...
for idx in Alist:
    print('A[%s] = %d' % (idx, AA[idx]) )

A[(0, 0, 0, 0)] = 0
A[(0, 0, 0, 1)] = 1
A[(0, 0, 0, 2)] = 2
A[(0, 0, 0, 3)] = 3
A[(0, 0, 1, 0)] = 4
A[(0, 0, 1, 1)] = 5
A[(0, 0, 1, 2)] = 6
A[(0, 0, 1, 3)] = 7
A[(0, 0, 2, 0)] = 8
A[(0, 0, 2, 1)] = 9
A[(0, 0, 2, 2)] = 10
A[(0, 0, 2, 3)] = 11
A[(0, 1, 0, 0)] = 12
A[(0, 1, 0, 1)] = 13
A[(0, 1, 0, 2)] = 14
A[(0, 1, 0, 3)] = 15
A[(0, 1, 1, 0)] = 16
A[(0, 1, 1, 1)] = 17
A[(0, 1, 1, 2)] = 18
A[(0, 1, 1, 3)] = 19
A[(0, 1, 2, 0)] = 20
A[(0, 1, 2, 1)] = 21
A[(0, 1, 2, 2)] = 22
A[(0, 1, 2, 3)] = 23
A[(1, 0, 0, 0)] = 24
A[(1, 0, 0, 1)] = 25
A[(1, 0, 0, 2)] = 26
A[(1, 0, 0, 3)] = 27
A[(1, 0, 1, 0)] = 28
A[(1, 0, 1, 1)] = 29
A[(1, 0, 1, 2)] = 30
A[(1, 0, 1, 3)] = 31
A[(1, 0, 2, 0)] = 32
A[(1, 0, 2, 1)] = 33
A[(1, 0, 2, 2)] = 34
A[(1, 0, 2, 3)] = 35
A[(1, 1, 0, 0)] = 36
A[(1, 1, 0, 1)] = 37
A[(1, 1, 0, 2)] = 38
A[(1, 1, 0, 3)] = 39
A[(1, 1, 1, 0)] = 40
A[(1, 1, 1, 1)] = 41
A[(1, 1, 1, 2)] = 42
A[(1, 1, 1, 3)] = 43
A[(1, 1, 2, 0)] = 44
A[(1, 1, 2, 1)] = 45
A[(1, 1, 2, 2)] = 46
A[(1, 1, 2, 3)] = 47


In [5]:
mydict=[]  # Creating a parameter dictionary
for i in range(n): 
    mydict.append({})
    for j in  range( len(plist[i]) ):
        mydict[i][plist[i][j]] = j
mydict

[{'A1': 0, 'A2': 1},
 {'B1': 0, 'B2': 1},
 {'C1': 0, 'C2': 1, 'C3': 2},
 {'D1': 0, 'D2': 1, 'D3': 2, 'D4': 3}]

In [35]:
import numpy as np
import pandas as pd
# Creating a 2 dimensional numpy array
data= np.array([[ 5.8,2.8], [ 6.0,2.2]])
print(data)

#Creating pandas dataframe from numpy array
dataset = pd.DataFrame({'Column1':data[:,0],'Column2':data[:,1]})
print(dataset)

#Creating pandas dataframe from numpy array
dataset2 = pd.DataFrame({'Column1':range(2), AA[:,0],'Column2':AA[:,1]})
print(dataset2)

[[5.8 2.8]
 [6.  2.2]]
   Column1  Column2
0      5.8      2.8
1      6.0      2.2


ValueError: If using all scalar values, you must pass an index

In [36]:
import pandas as pd
from numpy.random import randint
df = pd.DataFrame(columns=['lib', 'qty1', 'qty2'])
for i in range(5):
    df.loc[i] = ['name' + str(i)] + list(randint(10, size=2))
df    

lib qty1 qty2
0  name0    9    5
1  name1    9    5
2  name2    2    7
3  name3    6    0
4  name4    5    0

In [70]:
import pandas as pd
import random as rand
df = pd.DataFrame(columns=['A', 'B', 'C', 'D', 'V'])

i=0
for idx in Alist:
    a, b, c, d = idx
    a, b = plist[0][a], plist[1][b]
    df.loc[i] = [a, b, c, d, rand.uniform(0.5, 1)]
    i += 1
#display( df.head(5), df.tail(3) ) 
df.sort_values(by=['V'], ascending=False)

A   B  C  D         V
35  A2  B1  2  3  0.990738
24  A2  B1  0  0  0.962206
16  A1  B2  1  0  0.956361
19  A1  B2  1  3  0.950050
0   A1  B1  0  0  0.946473
9   A1  B1  2  1  0.945736
7   A1  B1  1  3  0.904997
3   A1  B1  0  3  0.901096
45  A2  B2  2  1  0.894555
22  A1  B2  2  2  0.889443
11  A1  B1  2  3  0.882518
39  A2  B2  0  3  0.882184
4   A1  B1  1  0  0.876580
42  A2  B2  1  2  0.872612
29  A2  B1  1  1  0.870786
10  A1  B1  2  2  0.862220
46  A2  B2  2  2  0.821461
47  A2  B2  2  3  0.819696
6   A1  B1  1  2  0.814124
30  A2  B1  1  2  0.800671
44  A2  B2  2  0  0.787750
36  A2  B2  0  0  0.776058
23  A1  B2  2  3  0.775265
15  A1  B2  0  3  0.768675
20  A1  B2  2  0  0.740659
41  A2  B2  1  1  0.736962
2   A1  B1  0  2  0.735033
12  A1  B2  0  0  0.726126
38  A2  B2  0  2  0.722442
27  A2  B1  0  3  0.714677
1   A1  B1  0  1  0.714361
32  A2  B1  2  0  0.709120
43  A2  B2  1  3  0.636808
28  A2  B1  1  0  0.633721
17  A1  B2  1  1  0.623963
13  A1  B2  0  1  0.623681
14  A1  B2  0  2  0.623218
26  A2  B1  0  2  0.608870
33  A2  B1  2  1  0.597625
40  A2  B2  1  0  0.589736
34  A2  B1  2  2  0.577918
21  A1  B2  2  1  0.577095
18  A1  B2  1  2  0.540570
31  A2  B1  1  3  0.530378
8   A1  B1  2  0  0.523785
5   A1  B1  1  1  0.514725
25  A2  B1  0  1  0.506017
37  A2  B2  0  1  0.502415

In [6]:
(a, b, c, d) = Alist[5]
print(a, b, c, d)

0 0 1 1


In [7]:
import itertools
for comb in itertools.combinations_with_replacement(range(3, -1, -1), 3):
        print(comb)

(3, 3, 3)
(3, 3, 2)
(3, 3, 1)
(3, 3, 0)
(3, 2, 2)
(3, 2, 1)
(3, 2, 0)
(3, 1, 1)
(3, 1, 0)
(3, 0, 0)
(2, 2, 2)
(2, 2, 1)
(2, 2, 0)
(2, 1, 1)
(2, 1, 0)
(2, 0, 0)
(1, 1, 1)
(1, 1, 0)
(1, 0, 0)
(0, 0, 0)


In [8]:
counts = [1, 2, 3]
ranges = [range(x) for x in counts]
for i in itertools.product(*ranges):
    print(i)

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)


In [9]:
if 3 < 4 : x = 5

In [10]:
x

5

In [11]:
plist

[['A1', 'A2'], ['B1', 'B2'], ['C1', 'C2', 'C3'], ['D1', 'D2', 'D3', 'D4']]

In [13]:
plist[1][1]

'B2'

In [14]:
Alist

[(0, 0, 0, 0),
 (0, 0, 0, 1),
 (0, 0, 0, 2),
 (0, 0, 0, 3),
 (0, 0, 1, 0),
 (0, 0, 1, 1),
 (0, 0, 1, 2),
 (0, 0, 1, 3),
 (0, 0, 2, 0),
 (0, 0, 2, 1),
 (0, 0, 2, 2),
 (0, 0, 2, 3),
 (0, 1, 0, 0),
 (0, 1, 0, 1),
 (0, 1, 0, 2),
 (0, 1, 0, 3),
 (0, 1, 1, 0),
 (0, 1, 1, 1),
 (0, 1, 1, 2),
 (0, 1, 1, 3),
 (0, 1, 2, 0),
 (0, 1, 2, 1),
 (0, 1, 2, 2),
 (0, 1, 2, 3),
 (1, 0, 0, 0),
 (1, 0, 0, 1),
 (1, 0, 0, 2),
 (1, 0, 0, 3),
 (1, 0, 1, 0),
 (1, 0, 1, 1),
 (1, 0, 1, 2),
 (1, 0, 1, 3),
 (1, 0, 2, 0),
 (1, 0, 2, 1),
 (1, 0, 2, 2),
 (1, 0, 2, 3),
 (1, 1, 0, 0),
 (1, 1, 0, 1),
 (1, 1, 0, 2),
 (1, 1, 0, 3),
 (1, 1, 1, 0),
 (1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 2, 0),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3)]

In [15]:
Blist[0,0,0,0] = 3

NameError: name 'Blist' is not defined

In [22]:
import numpy as np
AA = np.arange(24)
AA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
AA.shape= (4,6)
AA

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])